(() => {
  'use strict';
  const icons = {
    grid:'<rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/>',
    swords:'<path d="m4 3 8 8-3 3-8-8V3h3Zm16 0-8 8m-1 4 6 6m-2-3 3-3M3 21l6-6m-3 3-3-3m12-6 3-3V3h3v3l-3 3"/>',
    trend:'<path d="m3 17 6-6 4 3 8-10m-6 0h6v6"/>',
    brain:'<path d="M12 4c-4-4-9 0-7 4-4 1-4 7 0 8-1 4 4 6 7 3V4Zm0 0c4-4 9 0 7 4 4 1 4 7 0 8 1 4-4 6-7 3M8 8l4 3m4-3-4 3M7 15l5-2 5 2"/>',
    squad:'<circle cx="9" cy="8" r="3"/><path d="M2 21v-3c0-3 3-5 7-5s7 2 7 5v3M16 4c5 0 5 7 0 7m3 3c3 1 3 4 3 7"/>',
    layers:'<path d="m12 2 10 6-10 6L2 8l10-6Zm-10 11 10 6 10-6M2 18l10 5 10-5"/>',
    compass:'<circle cx="12" cy="12" r="9"/><path d="m16 8-2 6-6 2 2-6 6-2Z"/>',
    settings:'<path d="M3 6h18M3 12h18M3 18h18"/><circle cx="8" cy="6" r="2"/><circle cx="16" cy="12" r="2"/><circle cx="8" cy="18" r="2"/>',
    bell:'<path d="M18 8a6 6 0 0 0-12 0c0 6-3 7-3 9h18c0-2-3-3-3-9M10 21h4"/>',
    target:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>',
    arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',
    external:'<path d="M7 17 18 6M7 6h11v11"/>',
    check:'<path d="m5 12 4 4L19 6"/>',
    shield:'<path d="m12 2 9 4v6c0 6-9 10-9 10S3 18 3 12V6l9-4Z"/><path d="m7 12 3 3 7-7"/>',
    fire:'<path d="M12 2c1 7 7 7 7 13a7 7 0 0 1-14 0c0-3 2-6 4-8 0 4 1 5 2 5 2-3 2-5 1-10Z"/>',
    flag:'<path d="M5 22V3m0 0c5-5 9 5 15 0v11c-6 5-10-5-15 0"/>',
    pin:'<path d="m8 3 9 1-2 6 3 5-5 1-6-3-3-4 5-1-1-5Zm2 12-6 6"/>',
    film:'<rect x="3" y="4" width="18" height="16" rx="1"/><path d="M7 4v16M17 4v16M3 9h4M3 15h4M17 9h4M17 15h4m-7-6-3 3 3 3Z"/>',
    lock:'<rect x="5" y="10" width="14" height="11" rx="1"/><path d="M8 10V6a4 4 0 0 1 8 0v4M12 14v3"/>',
    trophy:'<path d="M7 3h10v6c0 7-10 7-10 0V3Zm10 2h4v3c0 4-4 4-4 4M7 5H3v3c0 4 4 4 4 4m5 2v6m-5 1h10"/>',
    clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l4 3"/>',
    x:'<path d="m6 6 12 12M6 18 18 6"/>',
    spark:'<path d="m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3 3-7Z"/>',
    eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>'
  };
  const icon = name => `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${icons[name] || icons.spark}</svg>`;
  const $ = selector => document.querySelector(selector);
  const escapeHTML = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const state = { tier:'plus', billing:'monthly', tab:'prepare', role:'adc', selectedMatch:0, event:1, tour:0, pinned:false, challenge:false };
  try { state.pinned = localStorage.getItem('opclimb-pinned-focus') === 'true'; } catch {}
  let toastTimer, lastTrigger;
  const nav = [
    ['overview','Overview','grid'],['match-room','Match room','swords'],['climb','My climb','trend'],['coach-memory','Coach memory','brain','PRO'],['squad','Squad arena','squad'],['plans','Plans & unlocks','layers']
  ];
  const mobile = [['overview','Home','grid'],['match-room','Match','swords'],['climb','Climb','trend'],['coach-memory','Coach','brain'],['plans','Unlocks','layers']];
  const routes = Object.fromEntries(nav.map(n=>[n[0],n[1]]));
  const tierLevel = { free:0,plus:1,pro:2 };
  const has = tier => tierLevel[state.tier] >= tierLevel[tier];
  const tag = (text,type='') => `<span class="tag ${type}">${text}</span>`;
  const portrait = (name,extra='') => `<span class="champion-avatar ${name.toLowerCase()} ${extra}" style="background-image:url('assets/${name.toLowerCase()}-splash.jpg')" role="img" aria-label="${name}"></span>`;
  const btn = (text,route,kind='')=>`<button class="btn ${kind}" data-route="${route}">${text} ${icon('arrow')}</button>`;
  const head = (eyebrow,title,copy,action='')=>`<header class="page-head"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1>${copy?`<p>${copy}</p>`:''}</div>${action}</header>`;
  const progress = (value,label) => `<div class="progress-track" role="progressbar" aria-label="${label}" aria-valuenow="${value}" aria-valuemin="0" aria-valuemax="100"><span style="width:${value}%"></span></div>`;
  const lockedBanner = (tier,feature)=>has(tier)?`<div class="access-banner">${icon('check')}<p><b>${feature}</b> is included in your ${state.tier.toUpperCase()} preview. All examples are illustrative.</p></div>`:`<div class="access-banner">${icon('lock')}<p><b>${feature} unlocks with ${tier.toUpperCase()}.</b> Explore an example before you choose a plan.</p><button class="btn btn-small" data-upgrade="${tier}">See the unlocks ${icon('arrow')}</button></div>`;
  const matches = [
    {champ:'Jinx',win:true,kda:'8 / 2 / 9',duration:'32:18',lp:'+24',cue:'Focus held',time:'Example game 01',summary:'Your damage found its window.',quote:'You kept the first reset clean. At dragon, you moved forward before the second threat was committed. At Baron, you waited and made the better read. Keep that decision for the next queue.'},
    {champ:'Ashe',win:false,kda:'3 / 6 / 11',duration:'28:42',lp:'−21',cue:'Review ready',time:'Example game 02',summary:'The result is not the whole story.',quote:'The early lane was controlled, but you stayed for one extra wave after your support recalled. That isolated death broke your first-reset focus. Next game, use your support’s recall as the cue to check your own exit.'},
    {champ:'Caitlyn',win:true,kda:'7 / 3 / 6',duration:'30:06',lp:'+23',cue:'Focus held',time:'Example game 03',summary:'A calm reset created your next play.',quote:'You built a wave, recalled with your support and returned without gifting a fight. The useful habit was planning the reset before you were forced into it—not simply winning the lane.'}
  ];
  const roleData = {
    adc:{label:'ADC',champ:'Jinx',matchup:'Jinx + Lulu into Draven + Nautilus',focus:'Protect the first reset.',cue:'Keep the wave. Keep your HP.',why:'Leave the extra trade. Recall with a safe wave instead of giving the lane an early opening.',cards:[['WIN LANE','Respect the first all-in.','Stay behind the wave when the hook is available. A missed hook is an opportunity to reassess, not an automatic invitation to fight.'],['WIN THE FIGHT','Track both threats.','Do not move forward just because the first engage ended. Keep the second access threat in view before committing.'],['YOUR JOB','Make the fight long.','Start with the safe target. Stay alive long enough to find a reset, rather than chasing the back line.']]},
    jungle:{label:'Jungle',champ:'Jinx',matchup:'Jungle scenario · bot-side objective setup',focus:'Prepare the objective before the timer.',cue:'Check lanes. Then contest.',why:'Your route should buy time to set up vision and check lane priority before the objective becomes a fight.',cards:[['FIRST ROUTE','Path with a reason.','Choose a route around available camps and a realistic lane opportunity. Do not cross the map for a play that has already ended.'],['OBJECTIVE','Check who can move.','Look at the adjacent waves and the enemy jungler’s last known position before committing to a contest.'],['YOUR JOB','Trade when you cannot contest.','If nearby lanes cannot move safely, look for a useful cross-map trade instead of forcing your team into a losing setup.']]},
    mid:{label:'Mid',champ:'Jinx',matchup:'Mid-lane scenario · first river rotation',focus:'Buy the right to move.',cue:'Wave first. Then river.',why:'A rotation has a cost. Check the wave and missing threats before giving up lane resources.',cards:[['WIN LANE','Know your next wave.','Plan your trade around the wave state and your available cooldowns. Keep an exit instead of spending everything for a small hit.'],['MAP PLAY','Move with information.','Check who is missing and where your jungler can support you. Do not turn a late rotation into an isolated face-check.'],['YOUR JOB','Keep the follow-up.','In the fight, identify the target your team can actually reach and save the cooldown that lets you contribute safely.']]},
    top:{label:'Top',champ:'Jinx',matchup:'Top-lane scenario · weak-side reset',focus:'Protect the wave when help is far away.',cue:'No vision. No extra trade.',why:'When your jungler is on the other side, preserving the lane can be more valuable than forcing another exchange.',cards:[['WIN LANE','Read the long lane.','Before committing forward, check how far you must retreat and when the enemy jungler was last seen.'],['RESET','Leave a playable wave.','Choose the safest achievable wave state before recalling. Do not spend your remaining health trying to force a perfect crash.'],['YOUR JOB','Give your team time.','If you cannot contest safely, communicate the pressure and keep your resources for the next playable window.']]},
    support:{label:'Support',champ:'Ashe',matchup:'Support scenario · river vision setup',focus:'Make vision a team action.',cue:'Move together. Ward together.',why:'Your next ward is useful only if you can place it without giving the enemy a free pick.',cards:[['WIN LANE','Match the wave state.','Choose your pressure window around the wave and your partner’s position, not just your own cooldowns.'],['VISION','Do not walk in first.','Use available information and teammate movement to enter dark areas. A missing enemy is a reason to slow down.'],['YOUR JOB','Protect the next damage window.','Track which threat can still reach your carry. Keep the tool that answers that threat rather than spending it on a low-value target.']]}
  };
  const eventSets = [
    [
      ['07:41','Lane','Correct restraint','You kept the reset safe instead of forcing the trade.','The enemy hook missed, but the wave and your health still made the extended trade poor. Holding position preserved your recall. Repeat the decision process, not just the result.'],
      ['18:26','Dragon','One decision to revisit','The first engage ended. The second threat had not.','You stepped into range after Nautilus committed while another enemy still had access to you. Before advancing, name both threats and check which one remains. This is an example coaching annotation, not a detected live event.'],
      ['31:03','Baron','A cleaner read','You waited for both threats before entering.','You held your position, watched the second commitment and then began dealing damage. This is evidence of a better decision in the example, not proof that the habit is mastered.']
    ],
    [
      ['06:12','Lane','A controlled start','You did not chase a low-value trade.','Your early restraint preserved enough health to keep farming. Keep checking the wave before a trade, even when the opponent looks vulnerable.'],
      ['09:48','Recall','The extra-wave trap','Your support recalled. You stayed exposed.','The extra wave was not worth staying alone without a safe exit. Use your lane partner’s reset as the prompt to reassess vision, health and the next enemy wave.'],
      ['22:15','Mid','A useful recovery','You waited for cover before collecting the wave.','After the early mistake, you took the safer wave with teammates nearby. Keep that reset discipline next game; a loss can still contain a repeatable improvement.']
    ],
    [
      ['08:05','Lane','Reset planned','You built the wave before leaving.','You started preparing the recall before your health forced it. That gave you more control over the wave and reduced the chance of an isolated death.'],
      ['17:40','Mid','Pressure without cover','You extended while your support was moving.','Even with lane pressure, your team’s position matters. Pause at the next wave until you know who can cover the forward step.'],
      ['25:12','Objective','Good discipline','You joined the setup with resources ready.','Your earlier recall meant you arrived with health and items instead of chasing a fight while low. Carry the preparation habit forward.']
    ]
  ];
  function matchRows(){return matches.map((m,i)=>`<button class="match-row ${m.win?'':'loss'}" data-match="${i}" aria-label="Review ${m.champ}, ${m.win?'victory':'defeat'}"><span class="result-line"></span>${portrait(m.champ)}<span class="match-name"><strong><span class="match-result">${m.win?'VICTORY':'DEFEAT'}</span> ${m.champ}</strong><small>Ranked solo · ${m.duration}</small></span><span class="kda">${m.kda}<small>${m.cue}</small></span>${icon('arrow')}</button>`).join('');}
  function overview(){return `${head('YOUR DAILY BRIEFING · EXAMPLE PLAYER','Welcome back, Kai.','One focus. Every game. Lasting improvement.','<button class="btn btn-small" data-action="tour">Explore the client '+icon('compass')+'</button>')}
    <div class="overview-top"><section class="mission"><img class="mission-art" src="assets/jinx-splash.jpg" alt="Jinx from League of Legends" fetchpriority="high"><div class="mission-copy"><div class="eyebrow">${icon('target')} YOUR NEXT GAME PLAN</div><h2>Less autopilot.<br><em>More intention.</em></h2><p><strong>Today’s focus: protect the first reset.</strong><br>Keep your HP. Keep the wave. Leave the extra trade.</p><div class="mission-actions"><button class="btn primary" data-room-tab="prepare">Open my match plan ${icon('arrow')}</button><button class="pin-btn" data-action="pin" aria-label="${state.pinned?'Unpin':'Pin'} current coaching focus" aria-pressed="${state.pinned}">${icon('pin')}</button></div></div><span class="art-credit">JINX · ADC / RIOT GAMES</span></section>
    <aside class="rank-card panel"><div class="eyebrow">YOUR RANKED SNAPSHOT</div><div class="rank-main"><span class="rank-emblem">${icon('trophy')}</span><div><h3>Gold IV</h3><p>47 <span class="muted">/ 100 LP</span></p></div></div><div class="rank-progress">${progress(47,'Progress towards 100 LP')}<div class="between" style="margin-top:8px"><small>Next division</small><small>Gold III</small></div></div><div class="rank-footer"><div><b class="mint">+94 LP</b><small>Last 20 games</small></div><div><b>60%</b><small>12W / 8L</small></div></div></aside></div>
    <div class="metric-row">${[['shield','70%','↑ 15pp','First reset protected'],['target','3 / 5','','Focus streak'],['trend','15%','↓ 25pp','Early-death games'],['fire','4 weeks','','Coaching journey']].map(([i,v,d,l])=>`<div class="panel metric"><span class="metric-icon">${icon(i)}</span><div><div class="value">${v}<span>${d}</span></div><p>${l}</p></div></div>`).join('')}</div>
    <section class="loop-section"><div class="section-head"><div><h2>Stop repeating. Start improving.</h2></div><span class="eyebrow">THE OP COACHING LOOP</span></div><div class="loop-grid">${[
      ['01','swords','Know your win condition','A plan for the lane, the fight and your job.','prepare','Prepare your next game'],
      ['02','film','Find the turning point','One decision to understand. Not twenty graphs.','review','Review your last game'],
      ['03','brain','Make the habit stick','A coach that remembers and tests your progress.','memory','Explore coaching memory']
    ].map(([n,i,t,p,action,cta])=>`<button class="panel loop-card" ${action==='memory'?'data-route="coach-memory"':`data-room-tab="${action}"`}><span class="loop-number">${n}</span>${icon(i)}<h3>${t}</h3><p>${p}</p><span class="link-label">${cta} ${icon('arrow')}</span></button>`).join('')}</div></section>
    <div class="overview-bottom"><section class="panel panel-padding"><div class="section-head"><h2>Every game has a lesson.</h2><button class="text-btn" data-room-tab="review">Match review ${icon('arrow')}</button></div><div class="match-list">${matchRows()}</div><p class="sample-caption">EXAMPLE MATCHES · SELECT A GAME TO SEE THE COACH’S READ</p></section><section class="panel panel-padding memory-card"><div class="eyebrow" style="color:var(--gold)">${has('pro')?'PRO PREVIEW':'NEXT UNLOCK · PRO'}</div><h2>Your coach shouldn’t start from zero.</h2><p>Keep your patterns, test your fixes and find the next thing worth working on.</p><div class="memory-mini"><span>Same mistake<br>Example trend</span><strong>4.1 → 1.6<small> / game</small></strong></div><button class="btn gold" data-route="coach-memory">See what Pro remembers ${icon('arrow')}</button></section></div>
    <section class="home-plan-strip">${icon('layers')}<div><h3>Find your focus. Build your game. Develop the player.</h3><p>Free → Plus → Pro. A clear step up in coaching, not a paywall on your achievements.</p></div>${btn('Compare unlocks','plans')}</section>`;}
  function prepare(){const r=roleData[state.role];return `<div class="room-top"><span class="eyebrow">CHOOSE AN EXAMPLE ROLE</span><div class="room-selector" aria-label="Example role">${Object.entries(roleData).map(([id,d])=>`<button class="role-chip" data-role="${id}" aria-pressed="${state.role===id}">${d.label}</button>`).join('')}</div></div><div class="match-banner">${state.role==='adc'?portrait('Jinx'):`<span class="metric-icon">${icon('swords')}</span>`}<div><h2>${r.matchup}</h2><p>Illustrative pre-game plan · no account or draft connected</p></div>${tag('45-second read','gray')}</div><div class="tactics-grid">${r.cards.map(([k,t,p],i)=>`<article class="panel tactic"><div class="tactic-number">0${i+1} / ${k}</div><h3>${t}</h3><p>${p}</p></article>`).join('')}</div><div class="personal-focus">${icon('target')}<div><span class="eyebrow accent">ONE PERSONAL FOCUS</span><h3>${r.focus}</h3><p>${r.why}</p><div class="dialog-actions"><button class="btn btn-small primary" data-room-tab="focus">Open focus card ${icon('arrow')}</button><button class="btn btn-small" data-action="pin">${state.pinned?'Unpin focus':'Pin focus for this device'}</button></div></div></div>`;}
  function focus(){const r=roleData[state.role];return `<div class="focus-surface"><div><span class="eyebrow">${r.label} · YOUR PRE-SELECTED FOCUS</span><h2>${r.cue}</h2><p>${r.why}</p><button class="btn primary" data-action="rehearse">Rehearse the decision ${icon('arrow')}</button></div></div><p class="footnote">A static reminder chosen before the game. This prototype does not read a live match, run an overlay or provide real-time game-state assistance.</p>`;}
  function review(){const m=matches[state.selectedMatch];const events=eventSets[state.selectedMatch];return `<div class="room-top"><span class="eyebrow">CHOOSE AN EXAMPLE MATCH</span><div class="room-selector">${matches.map((x,i)=>`<button class="role-chip" data-match="${i}" aria-pressed="${i===state.selectedMatch}">${x.champ} · ${x.win?'W':'L'}</button>`).join('')}</div></div><div class="match-banner">${portrait(m.champ)}<div><h2>${m.champ} · ${m.win?'Victory':'Defeat'}</h2><p>Ranked solo · ${m.duration} · ${m.kda} · ${m.lp} LP</p></div>${tag('Example debrief','gray')}</div><div class="review-grid"><article class="panel panel-padding"><div class="eyebrow accent">THE COACH’S READ</div><h2 class="review-quote">${m.summary}</h2><p class="muted">${m.quote}</p><div class="evidence-stats"><div class="evidence-stat"><b>${m.win?'Held':'Broken'}</b><span>First-reset focus</span></div><div class="evidence-stat"><b>1 decision</b><span>To carry forward</span></div><div class="evidence-stat"><b>3 moments</b><span>To understand</span></div></div></article><article class="panel panel-padding"><h2>Plan versus play</h2><div class="plan-check"><span>Lane plan</span>${tag(m.win?'Executed':'Partial',m.win?'':'gold')}</div><div class="plan-check"><span>Fight discipline</span>${tag('Partial','gold')}</div><div class="plan-check"><span>Personal focus</span>${tag(m.win?'Held':'Revisit',m.win?'':'red')}</div><div class="micro-box"><strong>Next queue</strong><p>${m.win?'Keep your first reset safe. Check the second threat before you step forward.':'When your support resets, reassess your own exit before taking one more wave.'}</p></div></article></div><section style="margin-top:27px"><div class="section-head"><h2>Three moments. One lesson.</h2><span class="meta">Tap a moment to inspect the read</span></div><div class="timeline">${events.map(([time,lane,title,summary],i)=>`<button class="event ${i===1?'mistake':''} ${i===state.event?'selected':''}" data-event="${i}" aria-pressed="${i===state.event}"><span class="time">${time} / ${lane.toUpperCase()}</span><h3>${title}</h3><p>${summary}</p></button>`).join('')}</div><div class="event-detail" aria-live="polite"><h3>${events[state.event][0]} · ${events[state.event][2]}</h3><p>${events[state.event][4]}</p></div></section><button class="text-btn note-line" data-route="coach-memory">${icon(has('pro')?'brain':'lock')} ${has('pro')?'See how this updates your coaching memory':'Pro connects this lesson to your season'} ${icon('arrow')}</button>`;}
  function matchRoom(){return `${head('PREPARE / PLAY WITH INTENT / REFLECT','Your match room.','One useful plan before. One clear lesson after.')}${lockedBanner('plus','The full match-by-match coaching loop')}<div class="tabs" role="tablist" aria-label="Coaching stages">${[['prepare','01 / Prepare'],['focus','02 / Focus card'],['review','03 / Review']].map(([id,text])=>`<button class="tab" id="tab-${id}" role="tab" aria-controls="room-panel" aria-selected="${state.tab===id}" tabindex="${state.tab===id?0:-1}" data-room-tab="${id}">${text}</button>`).join('')}</div><div class="tab-content" id="room-panel" role="tabpanel" aria-labelledby="tab-${state.tab}">${state.tab==='prepare'?prepare():state.tab==='focus'?focus():review()}</div>`;}
  function chart(){return `<svg class="chart" viewBox="0 0 650 220" role="img" aria-label="Illustrative net LP across 20 ranked games rises from zero to plus 94 LP"><defs><linearGradient id="chart-fill" x1="0" x2="0" y1="0" y2="1"><stop stop-color="#b6f66b" stop-opacity=".22"/><stop offset="1" stop-color="#b6f66b" stop-opacity="0"/></linearGradient></defs><path class="gridline" d="M34 30H620M34 80H620M34 130H620M34 180H620"/><text x="0" y="35">100</text><text x="8" y="135">33</text><text x="16" y="185">0</text><path class="chart-fill" d="M34 180 64 168 95 174 126 150 157 155 188 133 219 145 250 130 281 101 312 114 343 89 374 98 405 77 436 92 467 72 498 77 529 60 560 70 590 52 620 39V180H34Z"/><path class="chart-line" d="M34 180 64 168 95 174 126 150 157 155 188 133 219 145 250 130 281 101 312 114 343 89 374 98 405 77 436 92 467 72 498 77 529 60 560 70 590 52 620 39"/><circle class="point" cx="620" cy="39" r="6"/><text x="34" y="210">20 GAMES AGO</text><text x="548" y="210">+94 LP</text></svg>`;}
  function climb(){return `${head('YOUR DEVELOPMENT / NOT JUST YOUR SCORELINE','Better habits. Better evidence.','Track what you control. LP gives context; your decisions tell the story.',btn('Coach memory','coach-memory','btn-small'))}<div class="climb-grid"><article class="panel panel-padding"><div class="section-head"><div><span class="eyebrow">NET LP · LAST 20 RANKED GAMES</span><h2 style="margin-top:8px">The climb so far</h2></div>${tag('+94 LP')}</div>${chart()}<p class="sample-caption">ILLUSTRATIVE TREND · NOT AN OUTCOME GUARANTEE</p></article><article class="panel panel-padding"><div class="eyebrow accent">WHAT’S ACTUALLY CHANGING</div><h2 style="margin-top:10px">Fewer early gifts.</h2><div class="stat-highlight"><div><b class="muted">40%</b><small>Baseline · 8 / 20</small></div><span style="align-self:center">${icon('arrow')}</span><div><b class="mint">15%</b><small>Recent · 3 / 20</small></div></div><p class="muted" style="font-size:14px;margin-top:20px">Games with a death before 10 minutes. Two example 20-game windows, compared like for like.</p><div class="micro-box"><strong>Keep the evidence honest.</strong><p>This is a pattern to investigate, not proof that coaching caused every change.</p></div></article></div><section class="habits"><div class="section-head"><div><span class="eyebrow">EARNED THROUGH PRACTICE</span><h2 style="margin-top:6px">Your habit path</h2></div>${tag('1 active focus','gray')}</div><div class="panel"><div class="habit done"><span class="habit-index">${icon('check')}</span><div><h3>Check before entering river</h3><p>Established in familiar situations. Keep checking it in harder games.</p></div>${tag('Established')}</div><div class="habit"><span class="habit-index">02</span><div><h3>Protect the first reset</h3><p>3 of 5 clean games in this practice block.</p>${progress(60,'Three of five focus games')}</div>${tag('Your focus')}</div><div class="habit"><span class="habit-index">03</span><div><h3>Respect the second threat</h3><p>Next candidate. Introduce it when the current focus is reliable.</p></div>${tag('Next','gold')}</div><div class="habit"><span class="habit-index">04</span><div><h3>Keep the read under pressure</h3><p>Re-test the decision in a different matchup or fight.</p></div>${tag('Later','gray')}</div></div><p class="footnote">Habit progress is earned by practice, not bought. Pro adds season memory and an adaptive next-focus plan; it does not unlock a higher League rank.</p></section>`;}
  function memory(){return `${head('THE OP CLIMB DIFFERENCE / SEASON-LONG COACHING','A coach that remembers you.','Your last game is one chapter. Your development is the whole story.')}${lockedBanner('pro','Season memory and an adaptive next-focus plan')}<div class="climb-grid"><section class="panel panel-padding memory-panel"><div class="section-head"><h2>One habit. Four weeks of context.</h2>${tag('Pro','gold')}</div><div class="memory-timeline">${[
    ['WEEK 1','Find the repeat.','Example baseline: early deaths in 8 of 20 games. The coach selects first-reset discipline as the starting focus.'],
    ['WEEK 2','Practise one decision.','A short reminder supports the reset. Reviews ask what happened before the death, not just what the KDA says.'],
    ['WEEK 3','Use fewer prompts.','The same read appears without a reminder. The next test is whether it holds when the matchup changes.'],
    ['WEEK 4','Test it somewhere new.','Early-death games fall to 3 of 20 in the example. Keep checking the reset, then introduce the second-threat focus.']
  ].map(([w,t,p])=>`<div class="memory-event"><span>${w}</span><div><h3>${t}</h3><p>${p}</p></div></div>`).join('')}</div></section><aside class="panel panel-padding"><span class="eyebrow accent">WHAT THE COACH CARRIES FORWARD</span><h2 style="margin-top:12px">Not just your numbers.</h2><div class="criteria">${[['brain','Recurring decision patterns'],['target','Your current focus and why it matters'],['film','Examples that support—or challenge—the read'],['shield','When the habit holds without help'],['trend','The next useful test, not a random tip']].map(([i,t])=>`<div>${icon(i)}<span>${t}</span></div>`).join('')}</div><div class="micro-box"><strong>The goal: need less help.</strong><p>Progress means you make the read yourself, even in a new situation.</p></div><button class="btn ${has('pro')?'':'gold'}" style="width:100%;margin-top:20px" data-upgrade="pro">${has('pro')?'Review your Pro preview':'Explore Pro · £19.99/month'} ${icon('arrow')}</button></aside></div><div class="memory-outcomes">${[['REPEATED MISTAKE RATE','4.1 → 1.6','Per game in this illustrative coaching story.'],['SUPPORT NEEDED','HIGH → LOW','Fewer reminders; more independent decisions.'],['THE NEXT TEST','NEW MATCHUP','Can the player carry the same read into a different situation?']].map(([l,v,p])=>`<article class="panel outcome"><span class="eyebrow">${l}</span><strong>${v}</strong><p>${p}</p></article>`).join('')}</div><p class="footnote">These values demonstrate the proposed coaching experience. They are not measured results, live analysis or evidence of a working coaching engine.</p>`;}
  function squad(){return `${head('SQUAD ARENA / BETTER TOGETHER','Compete on the habit.','A weekly challenge that rewards the decision—not who can grind the most LP.')}${lockedBanner('plus','Weekly challenges and squad boards')}<div class="squad-grid"><section class="panel panel-padding"><div class="between"><span class="eyebrow accent">EXAMPLE WEEKLY CHALLENGE</span>${icon('flag')}</div><h2 class="challenge-title">Clean laning.<br>Clear intention.</h2><p class="muted">Complete five ranked games with no deaths before 10:00. Keep your focus even when the result goes against you.</p><div class="challenge-progress" aria-label="Three of five games complete"><span class="on"></span><span class="on"></span><span class="on"></span><span></span><span></span></div><div class="between"><span class="eyebrow">3 / 5 GAMES</span>${tag('2 to go')}</div><div class="micro-box"><strong>Reward: Clean Reset badge</strong><p>A recognition of the practice block. Not an LP boost or a paid-plan unlock.</p></div><button class="btn primary" style="margin-top:20px" data-action="challenge">${state.challenge?'Following in this preview':'Follow this challenge'} ${icon('flag')}</button></section><section class="panel panel-padding"><div class="section-head"><h2>The practice squad</h2>${tag('Sample','gray')}</div>${[['01','moonlane','Mid · Platinum IV','5 / 5'],['02','Kai#EUW','ADC · Gold IV','3 / 5'],['03','riverghost','Jungle · Gold II','2 / 5'],['04','veyra','Support · Silver I','2 / 5']].map(([n,name,role,score])=>`<div class="leaderboard-row ${name==='Kai#EUW'?'you':''}"><span>${n}</span><div><b>${name}${name==='Kai#EUW'?' · YOU':''}</b><small>${role}</small></div><strong>${score}</strong></div>`).join('')}<p class="footnote">Example members and completion counts. No invites, messages or real player records are used.</p></section></div>`;}
  const plans = {
    free:{label:'Free',purpose:'Find the thing worth fixing.',price:0,annual:0,benefit:'Your starting point: one clear focus.',features:['Last 20 ranked games overview','One personal focus','Basic progress dashboard'],button:'Explore Free'},
    plus:{label:'Plus',purpose:'Understand every game you play.',price:9.99,annual:99.90,benefit:'Add the complete match-by-match loop.',features:['Everything in Free','Pre-game match plans + focus cards','Full 5v5 post-game coaching reads','90 days of game history','Weekly challenges + squad boards'],button:'Preview Plus unlocks'},
    pro:{label:'Pro',purpose:'Develop the player across the season.',price:19.99,annual:199.90,benefit:'Add a coach that connects the dots.',features:['Everything in Plus','Season-long coaching memory','Automatic next-focus curriculum','Check whether each habit transfers','Evidence of independent decisions'],button:'Preview Pro unlocks'}
  };
  const comparison = [
    ['Personal focus','Included','Included','Included'],['Game history','Last 20 ranked games','90 days','Full season'],['Pre-game plans + focus cards','Preview only','Included','Included'],['Full post-game 5v5 reads','Preview only','Included','Included'],['Challenges + squad board','Preview only','Included','Included'],['Season coaching memory','Preview only','Preview only','Included'],['Adaptive next-focus curriculum','—','—','Included'],['Habit transfer checks','—','—','Included']
  ];
  function planPage(){return `${head('CHOOSE YOUR COACHING / KEEP YOUR PROGRESS','Your next level of support.','A better coaching toolkit—not a promise of free LP.')}<div class="plan-intro"><div><h2>Start with a focus.<br>Stay for the player you become.</h2><p>Three plans. A clear purpose for each.</p></div><div class="billing-toggle" role="group" aria-label="Billing period"><button data-billing="monthly" aria-pressed="${state.billing==='monthly'}">Monthly</button><button data-billing="annual" aria-pressed="${state.billing==='annual'}">Annual <span>Save 2 months</span></button></div></div><div class="plan-grid">${Object.entries(plans).map(([id,p],i)=>{const annual=state.billing==='annual',price=id==='free'?'0':(annual?p.annual/12:p.price).toFixed(2);return `<article class="plan-card ${id}"><div class="plan-number"><span>0${i+1} / COACHING TIER</span>${state.tier===id?tag('Previewing',id==='pro'?'gold':''):''}</div><h3>${p.label}</h3><p class="purpose">${p.purpose}</p><div class="plan-price">£${price}<span>${id==='free'?' / forever':' / month'}</span></div><p class="billing-note">${id==='free'?'No payment required.':annual?`£${p.annual.toFixed(2)} billed yearly. Save £${(p.price*12-p.annual).toFixed(2)}.`:`£${p.price.toFixed(2)} billed monthly. Proposed plan.`}</p><div class="plan-benefit">${icon(i===2?'brain':i===1?'swords':'target')}<span>${p.benefit}</span></div><ul>${p.features.map(f=>`<li>${icon('check')}<span>${f}</span></li>`).join('')}</ul><button class="btn ${id==='plus'?'primary':id==='pro'?'gold':''}" data-upgrade="${id}">${p.button} ${icon('arrow')}</button></article>`;}).join('')}</div><p class="footnote">Pricing and feature allocation are concept proposals for this UI. Previewing a plan changes this demo only; no subscription starts and no payment is taken.</p><details class="comparison"><summary>Compare every unlock, side by side</summary><div class="table-wrap" tabindex="0" aria-label="Scrollable feature comparison"><table><thead><tr><th scope="col">Your coaching toolkit</th><th scope="col">Free</th><th scope="col">Plus</th><th scope="col">Pro</th></tr></thead><tbody>${comparison.map(([f,...cells])=>`<tr><th scope="row">${f}</th>${cells.map(c=>`<td class="${c==='Included'?'yes':''}">${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div></details><div class="plan-faq"><article class="panel"><h3>Do I have to earn the next paid tier?</h3><p>No. Membership determines your coaching tools. Habits, badges and in-game rank are separate achievements—you earn them through practice.</p></article><article class="panel"><h3>Why move from Plus to Pro?</h3><p>Plus explains individual games. Pro connects those games, tests whether your fixes hold and chooses the next useful focus.</p></article></div>`;}
  const pages = {overview,'match-room':matchRoom,climb,'coach-memory':memory,squad,plans:planPage};
  function currentRoute(){const route=location.hash.slice(1);return pages[route]?route:'overview';}
  function render(restoreFocus=false){const route=currentRoute();$('#content').innerHTML=`<div class="page">${pages[route]()}</div>`;$('#view-name').textContent=routes[route];document.title=`${routes[route]} — OP Climb`;$('#desktop-nav').innerHTML=nav.map(([id,text,i,extra])=>`<a class="nav-link ${id===route?'active':''}" href="#${id}" ${id===route?'aria-current="page"':''}>${icon(i)}<span>${text}</span>${extra?`<span class="nav-extra">${extra}</span>`:''}</a>`).join('');$('#mobile-nav').innerHTML=mobile.map(([id,text,i])=>`<a class="${id===route?'active':''}" href="#${id}" ${id===route?'aria-current="page"':''}>${icon(i)}${text}</a>`).join('');$('#sidebar-tier').innerHTML=`${state.tier.toUpperCase()} <span>DEMO</span>`;$('#sidebar-next').textContent=state.tier==='free'?'Next unlock: the full match coaching loop.':state.tier==='plus'?'Next unlock: a coach that remembers.':'Your full season coaching preview.';$('#tier-preview').value=state.tier;if(restoreFocus)$('#content').focus({preventScroll:true});}
  function navigate(route){if(!pages[route])return;if(currentRoute()===route){render();}else{location.hash=route;}window.scrollTo({top:0,behavior:'auto'});}
  function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),3000);}
  function openDialog(body){const dialog=$('#detail-dialog');lastTrigger=document.activeElement;$('#dialog-content').innerHTML=body;if(!dialog.open)dialog.showModal();}
  function closeDialog(){const d=$('#detail-dialog');if(d.open)d.close();if(lastTrigger?.isConnected)lastTrigger.focus();}
  function dialogHead(kicker,title,copy){return `<span class="eyebrow accent">${kicker}</span><h2 id="dialog-title" class="dialog-title">${title}</h2><p class="dialog-copy">${copy}</p>`;}
  function dialogItem(i,title,copy){return `<div class="dialog-item">${icon(i)}<div><b>${title}</b><p>${copy}</p></div></div>`;}
  function upgrade(tier){if(!plans[tier])return;const p=plans[tier],annual=state.billing==='annual',cost=tier==='free'?'£0':annual?`£${p.annual.toFixed(2)} / year`:`£${p.price.toFixed(2)} / month`;openDialog(`${dialogHead('COACHING TIER / '+p.label,`${p.label}: ${p.purpose}`,`${cost}. ${tier==='free'?'Start with the essentials.':'See exactly what this tier adds before choosing.'}`)}<div class="dialog-items">${p.features.map((f,i)=>dialogItem(i===0?'layers':'check',f,i===0&&tier!=='free'?'Your previous tier’s tools stay included.':'Included in this proposed coaching tier.')).join('')}</div><p class="footnote">Interactive concept only. This button changes the preview; it does not create an account, start a subscription or take payment.</p><div class="dialog-actions"><button class="btn primary" data-preview="${tier}">Explore as ${p.label} ${icon('arrow')}</button><button class="btn" data-dialog-route="plans">Compare all plans</button></div>`);}
  const tourSteps=[['overview','Make the next game simple.','Your overview puts one personal focus first. Open your match plan, pin the reminder and inspect your last game.'],['match-room','Complete the coaching loop.','Prepare a short plan, rehearse the focus, then review the decision that mattered. Switch example roles to explore the approach.'],['coach-memory','See the real differentiator.','Pro remembers the habit, reduces support and tests whether the decision transfers to a new situation.'],['plans','Know exactly what you unlock.','Free finds a focus. Plus coaches each game. Pro develops the player across the season. Preview any tier without a payment.']];
  function tour(){const [route,title,copy]=tourSteps[state.tour];navigate(route);openDialog(`<div class="tour-counter">CLIENT TOUR · 0${state.tour+1} / 04</div>${dialogHead('EXPLORE OP CLIMB',title,copy)}<div class="dialog-actions"><button class="btn primary" data-action="tour-next">${state.tour===3?'Finish tour':'Next stop'} ${icon('arrow')}</button><button class="btn" data-action="close">Explore on my own</button></div>`);}
  function action(name){switch(name){case'close':closeDialog();break;case'pin':state.pinned=!state.pinned;try{localStorage.setItem('opclimb-pinned-focus',String(state.pinned));}catch{}render();toast(state.pinned?'Focus pinned on this device.':'Focus unpinned.');break;case'tour':state.tour=0;tour();break;case'tour-next':if(state.tour<3){state.tour++;tour();}else{closeDialog();toast('You’re ready to explore the client.');}break;case'challenge':if(!has('plus')){upgrade('plus');break;}state.challenge=!state.challenge;render();toast(state.challenge?'Following the example challenge in this preview.':'Example challenge unfollowed.');break;case'profile':openDialog(`${dialogHead('EXAMPLE PLAYER','Kai#EUW','Gold IV · 47 LP · ADC · EUW. This is a fictional player profile used to demonstrate the client.')}<div class="dialog-items">${dialogItem('eye','No account connection','No Riot account is connected and no personal match data has been loaded.')}${dialogItem('layers','Explore every tier','Use “Preview as” at the top to compare Free, Plus and Pro.')}</div><button class="btn primary" data-action="close">Back to the client</button>`);break;case'notifications':openDialog(`${dialogHead('EXAMPLE COACH FEED','Two things worth your attention.','A useful update should tell you what to do next.')}<div class="dialog-items">${dialogItem('film','Your last game has a lesson','Inspect the second-threat decision in the Jinx example.')}${dialogItem('brain','Your first-reset habit is improving','See how a coach would test whether the improvement transfers.')}</div><div class="dialog-actions"><button class="btn primary" data-dialog-route="match-room" data-set-tab="review">Read the debrief</button><button class="btn" data-dialog-route="coach-memory">See the pattern</button></div>`);break;case'rehearse':{const r=roleData[state.role];openDialog(`${dialogHead('10-SECOND REHEARSAL',r.focus,r.why)}<div class="dialog-items">${dialogItem('eye','Notice the cue',r.cue)}${dialogItem('target','Name your next decision','Say the action you will take before you queue. Keep it to one sentence.')}${dialogItem('film','Check it after the game','Look for an example of where you held the focus—or what pulled you away from it.')}</div><button class="btn primary" data-action="close">Got it. One focus.</button>`);break;}}}
  document.addEventListener('click',e=>{const el=e.target.closest('button,[data-route]');if(!el)return;if(el.dataset.action){action(el.dataset.action);return;}if(el.dataset.dialogRoute){if(el.dataset.setTab)state.tab=el.dataset.setTab;closeDialog();navigate(el.dataset.dialogRoute);return;}if(el.dataset.route){navigate(el.dataset.route);return;}if(el.dataset.roomTab){state.tab=el.dataset.roomTab;if(currentRoute()!=='match-room')navigate('match-room');else{render();$(`#tab-${state.tab}`)?.focus({preventScroll:true});}return;}if(el.dataset.role){state.role=el.dataset.role;render();$(`[data-role="${state.role}"]`)?.focus({preventScroll:true});return;}if(el.dataset.match!==undefined){state.selectedMatch=Number(el.dataset.match);state.event=1;state.tab='review';navigate('match-room');return;}if(el.dataset.event!==undefined){state.event=Number(el.dataset.event);render();$(`[data-event="${state.event}"]`)?.focus({preventScroll:true});return;}if(el.dataset.billing){state.billing=el.dataset.billing;render();$(`[data-billing="${state.billing}"]`)?.focus({preventScroll:true});return;}if(el.dataset.upgrade){upgrade(el.dataset.upgrade);return;}if(el.dataset.preview){const tier=el.dataset.preview;state.tier=tier;closeDialog();render();toast(`${plans[tier].label} preview active. No subscription or payment.`);return;}});
  document.addEventListener('keydown',e=>{if(e.target.getAttribute('role')!=='tab')return;const tabs=['prepare','focus','review'];let next=tabs.indexOf(state.tab);if(e.key==='ArrowRight')next=(next+1)%3;else if(e.key==='ArrowLeft')next=(next+2)%3;else if(e.key==='Home')next=0;else if(e.key==='End')next=2;else return;e.preventDefault();state.tab=tabs[next];render();$(`#tab-${state.tab}`).focus();});
  $('#tier-preview').addEventListener('change',e=>{state.tier=e.target.value;render();toast(`${plans[state.tier].label} demo selected. All data remains illustrative.`);});
  $('#detail-dialog').addEventListener('click',e=>{if(e.target!==e.currentTarget)return;const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();});
  $('#detail-dialog').addEventListener('cancel',()=>{if(lastTrigger?.isConnected)lastTrigger.focus();});
  window.addEventListener('hashchange',()=>render(true));
  document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
  render();
})();
